### ISSUE TITLE
init_concept_count - LookupError: unknown named parameter "" (under mssql)

### ISSUE THREAD

**Issue by actualben** [edencehealth/ohdsi-glue#45]
User running mssql cdmdb reports the following issue:

```
2024-04-11T09:32:09+0000 - glue - CRITICAL - uncaught LookupError exception: unknown named parameter ""
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-000: Traceback (most recent call last):
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-001:   File "<frozen runpy>", line 198, in _run_module_as_main
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-002:   File "<frozen runpy>", line 88, in _run_code
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-003:   File "/app/glue/__main__.py", line 39, in <module>
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-004:     main()
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-005:   File "/app/glue/__main__.py", line 35, in main
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-006:     glue_it(config)
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-007:   File "/app/glue/process.py", line 37, in glue_it
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-008:     init_concept_count.run(config, api)
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-009:   File "/app/glue/operations/init_concept_count.py", line 28, in run
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-010:     cdm_db.execute(ddl)
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-011:   File "/app/glue/db/multidb.py", line 205, in execute
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-012:     cursor.execute(final_query, filtered_params)
2024-04-11T09:32:09+0000 - glue - CRITICAL - traceback-013: LookupError: unknown named parameter ""
```

Everything in the rest of their report seems to indicate good connection to the database and that the DDL returned by webapi works fine when manually submitted to the db server.

**Comment by actualben** [comment]
I think the comment lines in the DDL, (for example: `/* analyses:`) look like a reference to a parameter with no name.

**Comment by ziporah** [comment]
hello @actualben any update on this issue ? This stops us from using glue to update the concepts tables on our mssql servers
